version: "3.8"
services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - /mnt/dockers/prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped
  homarr:
    container_name: homarr
    image: ghcr.io/ajnart/homarr:latest
    restart: unless-stopped
    volumes:
      - /mnt/dockers/homarr/configs:/app/data/configs
      - /mnt/dockers/homarr/icons:/app/public/icons
      - /mnt/dockers/homarr/data:/data
    ports:
      - '7575:7575'
networks: {}
